<?php return array(
    'root' => array(
        'pretty_version' => 'dev-main',
        'version' => 'dev-main',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../../../../',
        'aliases' => array(),
        'reference' => 'fa3fabec9d33050a8d8b4c4c81ae085f9be96e01',
        'name' => 'kygekteam/betterconfig',
        'dev' => true,
    ),
    'versions' => array(
        'consolidation/comments' => array(
            'pretty_version' => '1.0.2',
            'version' => '1.0.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../consolidation/comments',
            'aliases' => array(),
            'reference' => '908832ce3c8174a9414d741913543fd058aac5fb',
            'dev_requirement' => false,
        ),
        'kygekteam/betterconfig' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../../../../',
            'aliases' => array(),
            'reference' => 'fa3fabec9d33050a8d8b4c4c81ae085f9be96e01',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-ctype' => array(
            'pretty_version' => 'v1.24.0',
            'version' => '1.24.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-ctype',
            'aliases' => array(),
            'reference' => '30885182c981ab175d4d034db0f6f469898070ab',
            'dev_requirement' => false,
        ),
        'symfony/yaml' => array(
            'pretty_version' => 'v6.0.2',
            'version' => '6.0.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/yaml',
            'aliases' => array(),
            'reference' => 'ed602f38b8636a2ea21af760d2578f3d2f92fc60',
            'dev_requirement' => false,
        ),
    ),
);
